### ISSUE TITLE
automated deploy is broken

### ISSUE THREAD

**Issue by ahdinosaur** [pull-stream/pull-stream-docs#36]
https://travis-ci.org/pull-stream/pull-stream-docs/builds/244385632

full log: https://api.travis-ci.org/jobs/244385633/log.txt?deansi=true

```
/home/travis/build/pull-stream/pull-stream-docs/scripts/index.js:9
  if (err) throw err
           ^

Error: Bad credentials
    at Request._callback (/home/travis/build/pull-stream/pull-stream-docs/node_modules/ecosystem-docs/sync.js:139:37)
    at Request.self.callback (/home/travis/build/pull-stream/pull-stream-docs/node_modules/ecosystem-docs/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/travis/build/pull-stream/pull-stream-docs/node_modules/ecosystem-docs/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/travis/build/pull-stream/pull-stream-docs/node_modules/ecosystem-docs/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

**Comment by amsross** [comment]
Probably the same issue, but here are two additional builds that ran and failed, but due to a timeout:
* https://travis-ci.org/pull-stream/pull-stream-docs/builds/284941998
* https://travis-ci.org/pull-stream/pull-stream-docs/builds/284952434

**Comment by ahdinosaur** [comment]
yeah, sorry about that @amsross. _someone should_ deploy manually! :shipit:

**Comment by ahdinosaur** [comment]
DONE! thanks for your contributions @amsross, i see them on the website meow.

note: owners with deploy access will need to deploy manually on any future merges until this issue is resolved.

**Comment by brechtcs** [comment]
A quick reminder that [a couple of PRs](https://github.com/pull-stream/pull-stream-docs/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged) have been merged since the last manual deploy. (If people are too busy, I'd be happy to help maintain this by the way.)

**Comment by ahdinosaur** [comment]
@brechtcs thanks for the reminder, did a manual deploy, also added you as a contributor to this repository! :sparkles:

**Comment by elavoie** [comment]
I successfully added my module to module.md and then tried rebuilding the docs but I do not have credentials to do it. Can someone else do it or give me permission to do it myself? Thanks.

**Comment by brechtcs** [comment]
I gave it a try, but it seems I only have access to this repo, and not to `pull-stream/pull-stream.github.io`. I guess you ran into the same problem yourself.
